// 文件1: CodeGenerationTypes.cs
// 核心数据类型与配置类

using System;
using System.Collections.Generic;

namespace theArkitectPackage.Editor.CodeGeneration
{
    #region 配置类

    /// <summary>
    /// 代码生成选项 - 框架级配置容器
    /// </summary>
    public class CodeGenerationOptions
    {
        /// <summary>文件头部注释</summary>
        public string HeaderComment { get; set; } = "// <auto-generated />";
        
        /// <summary>命名空间配置</summary>
        public NamespaceConfiguration NamespaceConfig { get; set; } = new NamespaceConfiguration();
        
        /// <summary>类配置</summary>
        public ClassConfiguration ClassConfig { get; set; } = new ClassConfiguration();
        
        /// <summary>缩进字符串，默认为4个空格</summary>
        public string IndentString { get; set; } = "    ";
        
        /// <summary>行尾换行符</summary>
        public string NewLine { get; set; } = Environment.NewLine;
        
        /// <summary>是否使用readonly修饰符</summary>
        public bool UseReadonly { get; set; } = true;
        
        /// <summary>是否在头部包含生成时间戳</summary>
        public bool IncludeTimestamp { get; set; } = true;
        
        /// <summary>额外的using语句列表</summary>
        public List<string> AdditionalUsings { get; set; } = new List<string>();
    }

    /// <summary>
    /// 命名空间配置 - 支持嵌套命名空间和现代C#语法
    /// </summary>
    public class NamespaceConfiguration
    {
        /// <summary>命名空间名称（支持嵌套如"Company.Project.Module"）</summary>
        public string Name { get; set; } = "theArkitect.Generated";
        
        /// <summary>是否使用文件作用域命名空间（C# 10+特性）</summary>
        public bool UseFileScopedNamespace { get; set; } = false;
    }

    /// <summary>
    /// 类配置 - 完整的类定义控制
    /// </summary>
    public class ClassConfiguration
    {
        /// <summary>类名</summary>
        public string Name { get; set; } = "GeneratedConstants";
        
        /// <summary>访问修饰符</summary>
        public AccessModifier AccessModifier { get; set; } = AccessModifier.Public;
        
        /// <summary>是否为静态类</summary>
        public bool IsStatic { get; set; } = true;
        
        /// <summary>是否为部分类（partial）</summary>
        public bool IsPartial { get; set; } = false;
        
        /// <summary>类继承/实现列表（如"IConfigurable", "Singleton<T>"）</summary>
        public List<string> Inheritances { get; set; } = new List<string>();
        
        /// <summary>类特性（如"[Serializable]"）</summary>
        public List<string> Attributes { get; set; } = new List<string>();
        
        /// <summary>类XML文档注释</summary>
        public string XmlDocumentation { get; set; }
    }

    /// <summary>
    /// 成员配置基类 - 统一字段和属性的配置模型
    /// </summary>
    public abstract class MemberConfiguration
    {
        /// <summary>成员名称</summary>
        public string Name { get; set; }
        
        /// <summary>访问修饰符</summary>
        public AccessModifier AccessModifier { get; set; } = AccessModifier.Public;
        
        /// <summary>是否为静态成员</summary>
        public bool IsStatic { get; set; } = true;
        
        /// <summary>是否为只读</summary>
        public bool IsReadonly { get; set; } = true;
        
        /// <summary>是否为编译期常量（仅值类型）</summary>
        public bool IsConst { get; set; } = false;
        
        /// <summary>XML文档注释</summary>
        public string XmlDocumentation { get; set; }
        
        /// <summary>特性列表（如"[Range(0,100)]"）</summary>
        public List<string> Attributes { get; set; } = new List<string>();
    }

    /// <summary>
    /// 字段配置 - 用于生成字段定义
    /// </summary>
    public class FieldConfiguration : MemberConfiguration
    {
        /// <summary>字段类型（如"int", "string", "Vector3"）</summary>
        public string TypeName { get; set; }
        
        /// <summary>初始值字符串（将直接写入代码，如"100", "\"hello\"", "new Vector3(1,0,0)"）</summary>
        public string InitialValue { get; set; }
    }

    /// <summary>
    /// 属性配置 - 用于生成属性定义
    /// </summary>
    public class PropertyConfiguration : MemberConfiguration
    {
        /// <summary>属性类型</summary>
        public string TypeName { get; set; }
        
        /// <summary>Getter表达式（null则使用自动实现getter）</summary>
        public string GetterExpression { get; set; }
        
        /// <summary>Setter表达式（null则为只读属性）</summary>
        public string SetterExpression { get; set; }
        
        /// <summary>是否使用表达式体语法（=>）</summary>
        public bool UseExpressionBody { get; set; } = true;
    }

    /// <summary>
    /// 缓存系统专用数据结构
    /// </summary>
    public class CacheEntry
    {
        /// <summary>缓存文件名</summary>
        public string FileName { get; set; }
        
        /// <summary>数据类型全名</summary>
        public string TypeName { get; set; }
    }

    #endregion

    #region 枚举

    /// <summary>
    /// C#访问修饰符枚举
    /// </summary>
    public enum AccessModifier
    {
        Public,
        Internal,
        Protected,
        Private,
        ProtectedInternal,
        PrivateProtected
    }

    #endregion
}